GET http://localhost:3333/orders/1068083
Content-Type: application/json


###

GET http://localhost:3333/orders/1068083/all
Content-Type: application/json


###

GET http://localhost:3333/orders/1068083/payment/984417
Content-Type: application/json


###

GET http://localhost:3333/clients/321611/orders
Content-Type: application/json


###

POST http://localhost:3333/pay/bolecode
Content-Type: application/json


{
  "orcamentoId": 1068083,
  "paymentId": 984417
}

###

POST http://localhost:3333/pay/pix
Content-Type: application/json

{
  "orcamentoId": 1068024,
  "paymentId": 984393
}



###


POST http://localhost:3333/pay/card/token
Content-Type: application/json

{
  "number": "4539620659922097",
  "expiry": "12/2026",
  "cvv": "123",
  "name": "tiago henrique",
  "document": "01551660695"
  
}

###

POST http://localhost:3333/pay/card
Content-Type: application/json
Authorization: Bearer 1E31940324A54C84BAE877CB47C2DE03

{
    "orcamentoId": 1068083,
    "paymentId": 984417,
    "paymentMethod": {
        "type": "CREDIT_CARD",
        "installments": 1,
        "card": {
            "id": "CARD_34CEB8F7-F372-4628-B800-65DC90195D21",
            "securityCode": "123",
            "holder": {
                "name": "tiago henrique",
                "taxId": "01551660695"
            }
        }
    }
}

